/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Business.Employee;
import Business.Enterprise;
import Business.Manufacturer.ManufacturerEnterprise;
import Business.Network;
import Business.Roles.ManufacturerAdminRole;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karanmankodi
 */
public class CreateManufacturerJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    ManufacturerEnterprise manuEnt;
    UserAccount ua;
    Network network;
    /**
     * Creates new form CreateManufacturerJPanel
     */
    public CreateManufacturerJPanel(JPanel upcJPanel, Network network, Enterprise ent, UserAccount ua) {
        initComponents();
        this.manuEnt = (ManufacturerEnterprise)ent;
        this.upcJPanel = upcJPanel;
        this.ua = ua;
        this.network = network;
        entNameJTextField.setText(ent.getEnterpriseName());
        entTypeJTextField.setText(Business.Business.MANUFACTURER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        passwordJTextField = new javax.swing.JTextField();
        createAdminJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        entNameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entTypeJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ssnJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        contactNoJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("--- CREATE MANUFACTURER ADMIN ---");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setText("Username");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 90, -1));

        createAdminJButton.setText("CREATE ADMIN");
        createAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdminJButtonActionPerformed(evt);
            }
        });
        add(createAdminJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        backJButton.setText("<< BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, 20));

        entNameJTextField.setEditable(false);
        add(entNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 240, -1));

        jLabel3.setText("Enterprise Type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        entTypeJTextField.setEditable(false);
        add(entTypeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 240, -1));

        jLabel4.setText("Enterprise Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 310, -1));

        jLabel7.setText("SSN");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        add(ssnJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, -1));

        jLabel8.setText("Contact No");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
        add(contactNoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdminJButtonActionPerformed
        // TODO add your handling code here:
        
            Employee emp = manuEnt.getEmployeeDirectory().newEmployee();
            emp.setName(nameJTextField.getText());
            emp.setSsn(Integer.parseInt(ssnJTextField.getText()));
            emp.setContactNo(Integer.parseInt(contactNoJTextField.getText()));
            UserAccount ua1 = manuEnt.getUserAccountDirectory().newUserAccount();
            ua1.setEmployee(emp);
            ua1.setUsername(usernameJTextField.getText());
            ua1.setPassword(passwordJTextField.getText());
            ua1.setRole(new ManufacturerAdminRole());
            
            JOptionPane.showMessageDialog(null, "Done");
        
    }//GEN-LAST:event_createAdminJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upcJPanel.remove(this);
        CardLayout card = (CardLayout)upcJPanel.getLayout();
        card.previous(upcJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField contactNoJTextField;
    private javax.swing.JButton createAdminJButton;
    private javax.swing.JTextField entNameJTextField;
    private javax.swing.JTextField entTypeJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JTextField ssnJTextField;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
