/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Dispenser.DispenserEnterprise;
import Business.Dispenser.DispenserInventoryItem;
import Business.Dispenser.DispenserSalesOrganization;
import Business.Dispenser.DispenserSalesWorkRequest;
import Business.Enterprise;
import Business.Manufacturer.Drug;
import Business.Network;
import Business.Organization;
import Business.Patient;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanmankodi
 */
public class PurchaseDrugJPanel extends javax.swing.JPanel {

    private JPanel upcJPanel;
    private Patient p;
    Network network;
    private ArrayList<DispenserEnterprise> dispEntList;
    private Drug searchDrug;
    private DispenserInventoryItem dispII;

    /**
     * Creates new form PurchaseDrugJPanel
     */
    public PurchaseDrugJPanel(JPanel upcJPanel, Network network, Patient p) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.p = p;
        this.network = network;

        for (Network n : Business.Business.getInstance().getNetworkDritectory().getNetworkList()) {
            dispEntList = n.getEnterpriseDirectory().searchDispEnterprise();
            for (DispenserEnterprise e : dispEntList) {
                for (DispenserInventoryItem dii : e.getInvMgmtOrg().getInventory().getStoreInventory()) {
                    drugsJComboBox.addItem(dii.getDrug());
                }
            }
        }
        refreshWorkRequestTable();
        searchDrug = (Drug) drugsJComboBox.getSelectedItem();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        drugsJComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        catalogJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        quantityJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        quantityJTextField = new javax.swing.JTextField();
        manufacturerJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        priceJTextField = new javax.swing.JTextField();
        priceJLabel = new javax.swing.JLabel();
        manufacturerJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        orderJButton.setText("Order");
        orderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("--- PURCHASE DRUG ---");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        drugsJComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugsJComboBoxMouseClicked(evt);
            }
        });

        catalogJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Inventory Item ID", "Drug", "Price", "Quantity"
            }
        ));
        catalogJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catalogJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catalogJTable);

        jLabel2.setText("Select Drug");

        nameJLabel.setText("Name");

        idJLabel.setText("ID");

        quantityJLabel.setText("Quantity");

        nameJTextField.setEditable(false);

        quantityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityJTextFieldActionPerformed(evt);
            }
        });

        manufacturerJLabel.setText("Manufacturer");

        idJTextField.setEditable(false);

        priceJTextField.setEditable(false);

        priceJLabel.setText("Price");

        manufacturerJTextField.setEditable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(54, 54, 54)
                                .add(priceJLabel)
                                .add(10, 10, 10)
                                .add(priceJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(84, 84, 84)
                                .add(quantityJLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(quantityJTextField))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(nameJLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 192, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                                .add(idJLabel)
                                .add(18, 18, 18)
                                .add(idJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 271, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(manufacturerJLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(manufacturerJTextField))))
                    .add(layout.createSequentialGroup()
                        .add(134, 134, 134)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(drugsJComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(backJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(orderJButton)))
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, 0)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .add(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(drugsJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 190, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(idJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(idJLabel)
                    .add(nameJLabel)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(manufacturerJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(manufacturerJLabel))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(priceJLabel))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(priceJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(quantityJLabel)
                        .add(quantityJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(44, 44, 44)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(backJButton)
                    .add(orderJButton))
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(104, 104, 104)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .add(189, 189, 189)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshWorkRequestTable() {
        int rowCount = catalogJTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) catalogJTable.getModel()).removeRow(i);
        }

        for (Network n : Business.Business.getInstance().getNetworkDritectory().getNetworkList()) {
            dispEntList = n.getEnterpriseDirectory().searchDispEnterprise();
            for (DispenserEnterprise e : dispEntList) {
                for (DispenserInventoryItem dii : e.getInvMgmtOrg().getInventory().getStoreInventory()) {

                    Object row[] = new Object[4];
                    row[0] = dii;
                    row[1] = dii.getDrug();
                    row[2] = dii.getDrug().getPrice();
                    row[3] = dii.getQuantity();
                    ((DefaultTableModel) catalogJTable.getModel()).addRow(row);

                }
            }
        }
    }

    private void orderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderJButtonActionPerformed
        // TODO add your handling code here:
        if (searchDrug.getLicense().equals(Boolean.TRUE)) {
            for (Network n : Business.Business.getInstance().getNetworkDritectory().getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    if (e instanceof DispenserEnterprise) {
                        //System.out.println(e);
                        ArrayList<Organization> organizationList = e.getOrganizationDirectory().getOrganizationList();
                        if (e.equals(searchDrug.getDispEnt())) {
                            for (Organization o : organizationList) {
                                if (o instanceof DispenserSalesOrganization) {

                                    DispenserSalesWorkRequest request = (DispenserSalesWorkRequest) o.getWorkQueue().newWorkRequest(WorkRequest.Type.DispenserSalesWorkRequest);
                                    request.setPatient(p);
                                    request.setStatus(WorkRequest.Status.Sent);
                                    request.setDrug(searchDrug);
                                    request.setQuantity(Integer.parseInt(quantityJTextField.getText()));
                                    request.setDispEnt((DispenserEnterprise) e);

                                    JOptionPane.showMessageDialog(null, "Drug Ordered!");
                                }
                            }
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Drug not licensed for trade");
        }

    }//GEN-LAST:event_orderJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upcJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) upcJPanel.getLayout();
        cardLayout.previous(upcJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void drugsJComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugsJComboBoxMouseClicked
        // TODO add your handling code here:
        searchDrug = (Drug) drugsJComboBox.getSelectedItem();
        idJTextField.setText(String.valueOf(searchDrug.getId()));
        nameJTextField.setText(String.valueOf(searchDrug.getName()));
        priceJTextField.setText(String.valueOf(searchDrug.getPrice()));
        manufacturerJTextField.setText(String.valueOf(searchDrug.getManuEnt()));
    }//GEN-LAST:event_drugsJComboBoxMouseClicked

    private void catalogJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogJTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = catalogJTable.getSelectedRow();
        searchDrug = (Drug) catalogJTable.getValueAt(selectedRow, 1);
        idJTextField.setText(String.valueOf(searchDrug.getId()));
        nameJTextField.setText(String.valueOf(searchDrug.getName()));
        priceJTextField.setText(String.valueOf(searchDrug.getPrice()));
        manufacturerJTextField.setText(String.valueOf(searchDrug.getManuEnt()));
    }//GEN-LAST:event_catalogJTableMouseClicked

    private void quantityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityJTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable catalogJTable;
    private javax.swing.JComboBox drugsJComboBox;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manufacturerJLabel;
    private javax.swing.JTextField manufacturerJTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton orderJButton;
    private javax.swing.JLabel priceJLabel;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JLabel quantityJLabel;
    private javax.swing.JTextField quantityJTextField;
    // End of variables declaration//GEN-END:variables
}
