/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Wholesaler.ShippingManager;

import Business.Enterprise;
import Business.Network;
import Business.UserAccount;
import Business.Wholesaler.WholesalerEnterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karanmankodi
 */
public class WholesalerShippingManagerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    WholesalerEnterprise wholeEnt;
    UserAccount ua;
    Network network;
    /**
     * Creates new form SalesEmployeeWorkAreaJPanel
     */
    public WholesalerShippingManagerWorkAreaJPanel(JPanel upcJPanel, Network network, Enterprise ent, UserAccount ua) {
        this.upcJPanel = upcJPanel;
        this.wholeEnt = (WholesalerEnterprise) ent;
        this.ua = ua;
        this.network = network;
        if (wholeEnt.getLicense().equals(Boolean.FALSE)) {
            JOptionPane.showMessageDialog(null, "You are not licensed");
            upcJPanel.removeAll();
            CardLayout card = (CardLayout) upcJPanel.getLayout();
            card.previous(upcJPanel);
        } else {
            initComponents();
        }
        refreshCounter();
    }
    
    public void refreshCounter(){
        noOfPendingRequestsJTextField.setText(String.valueOf(wholeEnt.getMyOrganization(ua).getWorkQueue().getWorkRequestList().size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        workQueueJButton = new javax.swing.JButton();
        sentWorkQueueJButton = new javax.swing.JButton();
        noOfPendingRequestsJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("SHIPPING EMPLOYEE WORK AREA");

        workQueueJButton.setText("Work Queue");
        workQueueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workQueueJButtonActionPerformed(evt);
            }
        });

        sentWorkQueueJButton.setText("Sent Work Queue");
        sentWorkQueueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentWorkQueueJButtonActionPerformed(evt);
            }
        });

        noOfPendingRequestsJTextField.setEditable(false);

        jLabel2.setText("No of Pending Requests");

        refreshJButton.setText("Refresh Counter");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(refreshJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(noOfPendingRequestsJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(sentWorkQueueJButton)
                        .add(127, 127, 127))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(workQueueJButton)
                        .add(144, 144, 144))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel1)
                .add(52, 52, 52)
                .add(workQueueJButton)
                .add(32, 32, 32)
                .add(sentWorkQueueJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 93, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(noOfPendingRequestsJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(refreshJButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void workQueueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workQueueJButtonActionPerformed
        // TODO add your handling code here:
        JPanel panel = new WholesalerShippingEmployeeWorkQueueJPanel(upcJPanel, network, wholeEnt, ua);
        upcJPanel.add("SalesEmployeeWorkQueue", panel);
        CardLayout cardLayout = (CardLayout) upcJPanel.getLayout();
        cardLayout.next(upcJPanel);
    }//GEN-LAST:event_workQueueJButtonActionPerformed

    private void sentWorkQueueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentWorkQueueJButtonActionPerformed
        // TODO add your handling code here:
        JPanel panel = new WholesalerShippingManagerSentWorkQueueJPanel(upcJPanel, network, wholeEnt, ua);
        upcJPanel.add("SalesEmployeeSentWorkQueue", panel);
        CardLayout cardLayout = (CardLayout) upcJPanel.getLayout();
        cardLayout.next(upcJPanel);
    }//GEN-LAST:event_sentWorkQueueJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        refreshCounter();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField noOfPendingRequestsJTextField;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton sentWorkQueueJButton;
    private javax.swing.JButton workQueueJButton;
    // End of variables declaration//GEN-END:variables
}
