/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer.Admin;

import Business.Enterprise;
import Business.Manufacturer.Drug;
import Business.Manufacturer.ManufacturerEnterprise;
import Business.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karanmankodi
 */
public class ManufacturerAdminJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    ManufacturerEnterprise manuEnt;
    UserAccount ua;
    Network network;

    /**
     * Creates new form ManufacturerAdminJPanel
     */
    public ManufacturerAdminJPanel(JPanel upcJPanel, Network network, Enterprise ent, UserAccount ua) {
        this.upcJPanel = upcJPanel;
        this.manuEnt = (ManufacturerEnterprise) ent;
        this.ua = ua;
        this.network = network;
        if (manuEnt.getActive().equals(Boolean.FALSE)) {
            JOptionPane.showMessageDialog(null, "Manufacturer banned by FDA");
            upcJPanel.removeAll();
            CardLayout card = (CardLayout) upcJPanel.getLayout();
            card.previous(upcJPanel);
        } else {
            initComponents();
            if (manuEnt.getLicense().equals(Boolean.FALSE)) {
                addProdMngrJButton.setEnabled(false);
                addSalesEmpJButton1.setEnabled(false);
                addShipMngrJButton1.setEnabled(false);
            } else {
              //  Long licenseNo = manuEnt.getEntLicense().getLicenseNo();
               // licenseNoJTextField.setText(String.valueOf(licenseNo));


            }
        }

        for (Drug d : Business.Business.getInstance().getSuspectedDrugs()) {
            if (d.getManuEnt().equals(manuEnt)) {
                JOptionPane.showMessageDialog(null, "Your drug '" + d + "' has been held back from trade due to suspicions raised. Please check the list of Suspected Drugs for further details.");
            }
        }

        for (Drug d : Business.Business.getInstance().getFakeDrugs()) {
            if (d.getManuEnt().equals(manuEnt)) {
                JOptionPane.showMessageDialog(null, "Your drug '" + d + "' has been discontinued as it found as fake. Please check the list of Fake Drugs for further details.");
                JOptionPane.showMessageDialog(null, "You may submit a report of your drug '" + d + "' which will be evaluated. If we find the report varies from our findings, you may be cleared off charges.");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manufacturerEnterpriseJLabel = new javax.swing.JLabel();
        addProdMngrJButton = new javax.swing.JButton();
        addShipMngrJButton1 = new javax.swing.JButton();
        addSalesEmpJButton1 = new javax.swing.JButton();
        applyLicenseJButton = new javax.swing.JButton();
        sendReportJButton = new javax.swing.JButton();
        viewSuspectedDrugsJButton = new javax.swing.JButton();
        viewFakeDrugsJButton = new javax.swing.JButton();
        viewSalesReportJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manufacturerEnterpriseJLabel.setText("--- MANUFACTURER ENTERPRISE ---");
        add(manufacturerEnterpriseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 6, -1, -1));

        addProdMngrJButton.setText("Add Product Manager");
        addProdMngrJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdMngrJButtonActionPerformed(evt);
            }
        });
        add(addProdMngrJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 158, -1, -1));

        addShipMngrJButton1.setText("Add Shipping Manager");
        addShipMngrJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShipMngrJButton1ActionPerformed(evt);
            }
        });
        add(addShipMngrJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, -1, -1));

        addSalesEmpJButton1.setText("Add Sales Employee");
        addSalesEmpJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalesEmpJButton1ActionPerformed(evt);
            }
        });
        add(addSalesEmpJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, -1, -1));

        applyLicenseJButton.setText("Apply for License");
        applyLicenseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyLicenseJButtonActionPerformed(evt);
            }
        });
        add(applyLicenseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 206, -1, -1));

        sendReportJButton.setText("Send Evaluation Report");
        sendReportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendReportJButtonActionPerformed(evt);
            }
        });
        add(sendReportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 156, -1, -1));

        viewSuspectedDrugsJButton.setText("View Suspected Drugs");
        viewSuspectedDrugsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSuspectedDrugsJButtonActionPerformed(evt);
            }
        });
        add(viewSuspectedDrugsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 121, -1, -1));

        viewFakeDrugsJButton.setText("View Fake Drugs");
        viewFakeDrugsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFakeDrugsJButtonActionPerformed(evt);
            }
        });
        add(viewFakeDrugsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 86, -1, -1));

        viewSalesReportJButton.setText("View Sales Report");
        viewSalesReportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesReportJButtonActionPerformed(evt);
            }
        });
        add(viewSalesReportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addProdMngrJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdMngrJButtonActionPerformed
        // TODO add your handling code here: 

        CreateProductManagerJPanel cpmjp = new CreateProductManagerJPanel(upcJPanel, network, manuEnt, ua);
        upcJPanel.add("Create Product Manager", cpmjp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);

    }//GEN-LAST:event_addProdMngrJButtonActionPerformed

    private void addShipMngrJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShipMngrJButton1ActionPerformed
        // TODO add your handling code here:
        CreateShippingManagerJPanel csmjp = new CreateShippingManagerJPanel(upcJPanel, network, manuEnt, ua);
        upcJPanel.add("Create Shipping Manager", csmjp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);

    }//GEN-LAST:event_addShipMngrJButton1ActionPerformed

    private void addSalesEmpJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalesEmpJButton1ActionPerformed
        // TODO add your handling code here:
        CreateSalesEmployeeJPanel csejp = new CreateSalesEmployeeJPanel(upcJPanel, network, manuEnt, ua);
        upcJPanel.add("Create Sales Employee", csejp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);

    }//GEN-LAST:event_addSalesEmpJButton1ActionPerformed

    private void applyLicenseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyLicenseJButtonActionPerformed
        // TODO add your handling code here:

        ApplyForLicenseJPanel afljp = new ApplyForLicenseJPanel(upcJPanel, network, manuEnt, ua);
        upcJPanel.add("Apply for License", afljp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);

    }//GEN-LAST:event_applyLicenseJButtonActionPerformed

    private void sendReportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendReportJButtonActionPerformed
        // TODO add your handling code here:
        ManufacturerForensicReportJPanel mfrjp = new ManufacturerForensicReportJPanel(upcJPanel, network, manuEnt, ua);
        upcJPanel.add("Manufacturer Report", mfrjp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_sendReportJButtonActionPerformed

    private void viewSuspectedDrugsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSuspectedDrugsJButtonActionPerformed
        // TODO add your handling code here:
        ViewSuspectedDrugsJPanel vsdjp = new ViewSuspectedDrugsJPanel(upcJPanel, manuEnt);
        upcJPanel.add("View Suspected Drugs", vsdjp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_viewSuspectedDrugsJButtonActionPerformed

    private void viewFakeDrugsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFakeDrugsJButtonActionPerformed
        // TODO add your handling code here:
        ViewFakeDrugsJPanel vfdjp = new ViewFakeDrugsJPanel(upcJPanel);
        upcJPanel.add("View Fake Drugs", vfdjp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_viewFakeDrugsJButtonActionPerformed

    private void viewSalesReportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesReportJButtonActionPerformed
        // TODO add your handling code here:
        TotalSalesJPanel panel = new TotalSalesJPanel(upcJPanel, network, manuEnt, ua);
        upcJPanel.add("Total sales", panel);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_viewSalesReportJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProdMngrJButton;
    private javax.swing.JButton addSalesEmpJButton1;
    private javax.swing.JButton addShipMngrJButton1;
    private javax.swing.JButton applyLicenseJButton;
    private javax.swing.JLabel manufacturerEnterpriseJLabel;
    private javax.swing.JButton sendReportJButton;
    private javax.swing.JButton viewFakeDrugsJButton;
    private javax.swing.JButton viewSalesReportJButton;
    private javax.swing.JButton viewSuspectedDrugsJButton;
    // End of variables declaration//GEN-END:variables
}
