/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Dispenser.Admin;

import Business.Dispenser.DispenserEnterprise;
import Business.Enterprise;
import Business.FDA.FDAEnterprise;
import Business.FDA.EnterpriseLicenseRequest;
import Business.FDA.StateLicensingOrganization;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
import Business.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanmankodi
 */
public class ApplyForLicenseJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    DispenserEnterprise dispEnt;
    UserAccount ua;
    Network network;

    /**
     * Creates new form ApplyForLicenseJPanel
     */
    public ApplyForLicenseJPanel(JPanel upcJPanel, Network network, DispenserEnterprise dispEnt, UserAccount ua) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.dispEnt = dispEnt;
        this.ua = ua;
        this.network = network;

        nameJTextField.setText(dispEnt.getEnterpriseName());
        typeJTextField.setText(dispEnt.getType());
        line1JTextField.setText(dispEnt.getAddress().getLine1());
        cityJTextField.setText(dispEnt.getAddress().getCity());
        stateJTextField.setText(dispEnt.getAddress().getState());
        zipCodeJTextField.setText(String.valueOf(dispEnt.getAddress().getZipCode()));
        int rowCount = orgJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) orgJTable.getModel()).removeRow(i);
        }

        for (Organization o : dispEnt.getOrganizationDirectory().getOrganizationList()) {
            Object row[] = new Object[1];
            row[0] = o.getName();
            ((DefaultTableModel) orgJTable.getModel()).addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        typeJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        zipCodeJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        stateJTextField = new javax.swing.JTextField();
        cityJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        line1JTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        applyJButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        orgJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("State");

        jLabel7.setText("Zip Code");

        jLabel4.setText("Line 1");

        jLabel5.setText("City");

        jLabel1.setText("Enterprise Name");

        jLabel3.setText("Address :");

        jLabel2.setText("Enterprise Type");

        applyJButton.setText("Apply");
        applyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyJButtonActionPerformed(evt);
            }
        });

        orgJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Organizations"
            }
        ));
        jScrollPane3.setViewportView(orgJTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(typeJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(jLabel3))
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jLabel4)
                .add(200, 200, 200)
                .add(line1JTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jLabel5)
                .add(200, 200, 200)
                .add(cityJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel6)
                .add(200, 200, 200)
                .add(stateJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jLabel7)
                .add(200, 200, 200)
                .add(zipCodeJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 414, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(180, 180, 180)
                .add(applyJButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(typeJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel3)
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel4))
                    .add(line1JTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel5))
                    .add(cityJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel6))
                    .add(stateJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel7))
                    .add(zipCodeJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(6, 6, 6)
                .add(applyJButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyJButtonActionPerformed
        // TODO add your handling code here:
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof FDAEnterprise) {
                //System.out.println(e);
                ArrayList<Organization> organizationList = e.getOrganizationDirectory().getOrganizationList();
                for (Organization o : organizationList) {
                    if (o instanceof StateLicensingOrganization) {

                        EnterpriseLicenseRequest request = (EnterpriseLicenseRequest) o.getWorkQueue().newWorkRequest(WorkRequest.Type.EnterpriseLicenseRequest);
                        request.setSender(ua);
                        request.setEnt(dispEnt);
                        request.setStatus(WorkRequest.Status.Sent);
                        request.getEntLic().setAppName(nameJTextField.getText());
                        request.getEntLic().setAppType(typeJTextField.getText());
                        request.getEntLic().setAppLine1(line1JTextField.getText());
                        request.getEntLic().setAppCity(cityJTextField.getText());
                        request.getEntLic().setAppState(stateJTextField.getText());
                        request.getEntLic().setAppZipCode(Integer.parseInt(zipCodeJTextField.getText()));
                        request.getEntLic().setAppOrgList(dispEnt.getOrganizationDirectory().getOrganizationList());
                        dispEnt.setId(request.getEntLic().getLicenseNo());
                        JOptionPane.showMessageDialog(null, "Approval Request Generated!!!");
                    }
                }

            }

        }
    }//GEN-LAST:event_applyJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyJButton;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField line1JTextField;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTable orgJTable;
    private javax.swing.JTextField stateJTextField;
    private javax.swing.JTextField typeJTextField;
    private javax.swing.JTextField zipCodeJTextField;
    // End of variables declaration//GEN-END:variables
}
