/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Dispenser.Admin;

import Business.Dispenser.AdverseEffectsWorkRequest;
import Business.Dispenser.DispenserEnterprise;
import Business.Dispenser.DispenserInventoryItem;
import Business.Dispenser.DispenserSalesOrganization;
import Business.Dispenser.DispenserSalesWorkRequest;
import Business.Enterprise;
import Business.Manufacturer.Drug;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
import Business.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karanmankodi
 */
public class ChangePrescriptionJPanel extends javax.swing.JPanel {

    private JPanel upcJPanel;
    private AdverseEffectsWorkRequest req;
    private UserAccount ua;
    private ArrayList<DispenserEnterprise> dispEntList;
    private Drug d;
    Network network;
    
    /**
     * Creates new form ChangePrescriptionJPanel
     */
    public ChangePrescriptionJPanel(JPanel upcJPanel, UserAccount ua, AdverseEffectsWorkRequest req, Network network) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.ua = ua;
        this.req = req;
        this.network = network;

        dispEntList = network.getEnterpriseDirectory().searchDispEnterprise();

        for (DispenserEnterprise e : dispEntList) {
            for (DispenserInventoryItem dii : e.getInvMgmtOrg().getInventory().getStoreInventory()) {
                drugJComboBox.addItem(dii.getDrug());
            }
        }

        d = (Drug) drugJComboBox.getSelectedItem();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drugJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        placeRequestJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        quantityJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dosageJTextFild = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        drugJComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugJComboBoxMouseClicked(evt);
            }
        });

        jLabel1.setText("--- CHANGE PRESCRIPTION ---");

        jLabel2.setText("Select Drug");

        jLabel3.setText("Name");

        nameJTextField.setEditable(false);

        placeRequestJButton.setText("Change Prescription");
        placeRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeRequestJButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantity");

        jLabel5.setText("Dosage");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap(73, Short.MAX_VALUE)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(nameJTextField))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(drugJComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel5)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(quantityJTextField)
                            .add(dosageJTextFild))))
                .add(58, 58, 58))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(placeRequestJButton)
                .add(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(drugJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(quantityJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(dosageJTextFild, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                .add(placeRequestJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drugJComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugJComboBoxMouseClicked
        // TODO add your handling code here:
        Drug d = (Drug) drugJComboBox.getSelectedItem();
        nameJTextField.setText(d.getName());
    }//GEN-LAST:event_drugJComboBoxMouseClicked

    private void placeRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeRequestJButtonActionPerformed
        // TODO add your handling code here:
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof DispenserEnterprise) {
                //System.out.println(e);
                ArrayList<Organization> organizationList = e.getOrganizationDirectory().getOrganizationList();
                if (e.equals(d.getDispEnt())) {
                    for (Organization o : organizationList) {
                        if (o instanceof DispenserSalesOrganization) {

                            DispenserSalesWorkRequest request = (DispenserSalesWorkRequest) o.getWorkQueue().newWorkRequest(WorkRequest.Type.DispenserSalesWorkRequest);
                            request.setPatient(req.getPatient());
                            request.setStatus(WorkRequest.Status.Sent);
                            request.setDrug(d);
                            request.setQuantity(Integer.parseInt(quantityJTextField.getText()));
                            request.setDosage(dosageJTextFild.getText());
                            request.setDispEnt((DispenserEnterprise) e);
                            request.addIDtoList(request.getId());

                            JOptionPane.showMessageDialog(null, "Prescription Changed for Patient '" +request.getPatient()+ "'. Order placed for new prescription.");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_placeRequestJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dosageJTextFild;
    private javax.swing.JComboBox drugJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton placeRequestJButton;
    private javax.swing.JTextField quantityJTextField;
    // End of variables declaration//GEN-END:variables
}
