/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Dispenser.Admin;

import Business.Dispenser.AdverseEffectsWorkRequest;
import Business.Enterprise;
import Business.FDA.CDEROrganization;
import Business.FDA.FDAEnterprise;
import Business.FDA.ReportSuspicionWorkRequest;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
import Business.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanmankodi
 */
public class ComplaintDetailsJPanel extends javax.swing.JPanel {

    private JPanel upcJPanel;
    private UserAccount ua;
    private AdverseEffectsWorkRequest req;
    Network network;

    /**
     * Creates new form ComplaintDetailsJPanel
     */
    public ComplaintDetailsJPanel(JPanel upcJPanel, UserAccount ua, AdverseEffectsWorkRequest req, Network network) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.req = req;
        this.ua = ua;
        this.network = network;
        complaintIDJTextField.setText(String.valueOf(req.getId()));
        patientNameJTextField.setText(req.getPatient().getName());
        drugNameJTextField.setText(req.getDrug().getName());
        complaintJTextField.setText(req.getComments());

        int rowCount = sideEffectsJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) sideEffectsJTable.getModel()).removeRow(i);
        }
        for (String s : req.getDrug().getSideEffects()) {
            Object row[] = new Object[1];
            row[0] = s;
            ((DefaultTableModel) sideEffectsJTable.getModel()).addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientNameJTextField = new javax.swing.JTextField();
        changePrescriptionJButton = new javax.swing.JButton();
        reportSuspicionJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        drugNameJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        complaintIDJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        complaintJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sideEffectsJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("--- COMPLAINT DETAILS ---");

        jLabel2.setText("Patient Name");

        patientNameJTextField.setEditable(false);

        changePrescriptionJButton.setText("Change Prescription");
        changePrescriptionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePrescriptionJButtonActionPerformed(evt);
            }
        });

        reportSuspicionJButton.setText("Report Suspicion");
        reportSuspicionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSuspicionJButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Drug Name");

        drugNameJTextField.setEditable(false);

        jLabel5.setText("Complaint ID");

        complaintIDJTextField.setEditable(false);

        jLabel6.setText("Complaint");

        complaintJTextField.setEditable(false);

        sideEffectsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Expected Side Effects"
            }
        ));
        jScrollPane1.setViewportView(sideEffectsJTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(changePrescriptionJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(reportSuspicionJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6)
                                    .add(jLabel4)))
                            .add(jLabel5)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(patientNameJTextField)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, complaintIDJTextField)
                            .add(drugNameJTextField)
                            .add(complaintJTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(complaintIDJTextField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(patientNameJTextField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(drugNameJTextField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(complaintJTextField)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(changePrescriptionJButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(reportSuspicionJButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changePrescriptionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePrescriptionJButtonActionPerformed
        // TODO add your handling code here
        ChangePrescriptionJPanel cpjp = new ChangePrescriptionJPanel(upcJPanel, ua, req, network);
        upcJPanel.add("Change Prescription", cpjp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_changePrescriptionJButtonActionPerformed

    private void reportSuspicionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSuspicionJButtonActionPerformed
        // TODO add your handling code here:
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof FDAEnterprise) {
                for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof CDEROrganization) {
                        ReportSuspicionWorkRequest request = (ReportSuspicionWorkRequest) org.getWorkQueue().newWorkRequest(WorkRequest.Type.ReportSuspicionWorkRequest);
                        request.setDrug(req.getDrug());
                        request.addIDtoList(req.getId());
                        req.getDrug().setLicense(Boolean.FALSE);
                        Business.Business.getInstance().addSuspectedDrug(req.getDrug());
                        JOptionPane.showMessageDialog(null, "Drug '" +req.getDrug()+ "' Sent to Center for Drug Evaluation & Research for Evaluation");
                    }
                }
            }
        }
    }//GEN-LAST:event_reportSuspicionJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePrescriptionJButton;
    private javax.swing.JTextField complaintIDJTextField;
    private javax.swing.JTextField complaintJTextField;
    private javax.swing.JTextField drugNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientNameJTextField;
    private javax.swing.JButton reportSuspicionJButton;
    private javax.swing.JTable sideEffectsJTable;
    // End of variables declaration//GEN-END:variables
}
