/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer.ProductManager;

import Business.Enterprise;
import Business.Manufacturer.Drug;
import Business.Manufacturer.ManufacturerEnterprise;
import Business.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanmankodi
 */
public class ManageDrugsJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    ManufacturerEnterprise manuEnt;
    UserAccount ua;
    Network network;
    /**
     * Creates new form ManageDrugsJPanel
     */
    public ManageDrugsJPanel(JPanel upcJPanel, Network network, Enterprise ent, UserAccount ua) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.manuEnt = (ManufacturerEnterprise) ent;
        this.ua = ua;
        this.network = network;
        Refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        drugCatalogJTable = new javax.swing.JTable();
        viewDrugDetailJButton = new javax.swing.JButton();
        createDrugJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        thresholdJTextField = new javax.swing.JTextField();
        thresholdJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addQtyJTextField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        drugCatalogJTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        drugCatalogJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug Name", "Drug ID", "Quantity Available", "Threshold"
            }
        ));
        jScrollPane1.setViewportView(drugCatalogJTable);

        viewDrugDetailJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        viewDrugDetailJButton.setText("View Details");
        viewDrugDetailJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDrugDetailJButtonActionPerformed(evt);
            }
        });

        createDrugJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        createDrugJButton.setText("Create New Drug");
        createDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDrugJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refreshJButton.setMargin(new java.awt.Insets(2, 1, 2, 1));
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        deleteJButton.setText("Delete Drug");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Threshold");

        thresholdJButton.setText("Set Threshold");
        thresholdJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thresholdJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Add Quantity");

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("--- MANAGE DRUG CATALOG ---");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(174, 174, 174)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(refreshJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1))
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(thresholdJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(deleteJButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(thresholdJButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 43, Short.MAX_VALUE)
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(addQtyJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(addJButton))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(46, 46, 46)
                                .add(viewDrugDetailJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(createDrugJButton)))))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(backJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(31, 31, 31))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(refreshJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(thresholdJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(thresholdJButton)
                    .add(jLabel2)
                    .add(addQtyJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(addJButton))
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(deleteJButton)
                    .add(viewDrugDetailJButton)
                    .add(createDrugJButton))
                .add(61, 61, 61)
                .add(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDrugDetailJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDrugDetailJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugCatalogJTable.getSelectedRow();
        Drug selectedDrug = (Drug) drugCatalogJTable.getValueAt(selectedRow, 0);

        ViewDrugFactSheetJPanel vpdjp = new ViewDrugFactSheetJPanel(upcJPanel, selectedDrug);
        upcJPanel.add("ViewDrugDetails", vpdjp);
        CardLayout cardLayout = (CardLayout) upcJPanel.getLayout();
        cardLayout.next(upcJPanel);
    }//GEN-LAST:event_viewDrugDetailJButtonActionPerformed

    public void Refresh(){
        int rowCount = drugCatalogJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) drugCatalogJTable.getModel()).removeRow(i);
        }


        ArrayList<Drug> drugList = manuEnt.getProdMgmtOrg().getDrugCatalog().getDrugList();
        for (Drug d : drugList) {
            Object row[] = new Object[4];
            row[0] = d;
            row[1] = d.getId();
            row[2] = d.getAvailable();
            row[3] = d.getThreshold();

            ((DefaultTableModel) drugCatalogJTable.getModel()).addRow(row);
        }
    }
    private void createDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDrugJButtonActionPerformed
        INDJPanel apjp = new INDJPanel(upcJPanel, network, manuEnt, ua);
        upcJPanel.add("CreateNewDrug", apjp);
        CardLayout cardLayout = (CardLayout) upcJPanel.getLayout();
        cardLayout.next(upcJPanel);
    }//GEN-LAST:event_createDrugJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upcJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) upcJPanel.getLayout();
        cardLayout.previous(upcJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugCatalogJTable.getSelectedRow();
        if (selectedRow < 0 || selectedRow > drugCatalogJTable.getRowCount()) {
            return;
        }
        Drug selectedDrug = (Drug) drugCatalogJTable.getValueAt(selectedRow, 0);
        manuEnt.getProdMgmtOrg().getDrugCatalog().deleteDrug(selectedDrug);
        Refresh();
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void thresholdJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thresholdJButtonActionPerformed
            // TODO add your handling code here:
        int selectedRow = drugCatalogJTable.getSelectedRow();
        Drug drug = (Drug)drugCatalogJTable.getValueAt(selectedRow, 0);
        drug.setThreshold(Integer.parseInt(thresholdJTextField.getText()));
        Refresh();
    }//GEN-LAST:event_thresholdJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugCatalogJTable.getSelectedRow();
        Drug drug = (Drug)drugCatalogJTable.getValueAt(selectedRow, 0);
        manuEnt.getProdMgmtOrg().getDrugCatalog().addQuantity(drug, Integer.parseInt(addQtyJTextField.getText()));
        Refresh();
    }//GEN-LAST:event_addJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JTextField addQtyJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createDrugJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JTable drugCatalogJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton thresholdJButton;
    private javax.swing.JTextField thresholdJTextField;
    private javax.swing.JButton viewDrugDetailJButton;
    // End of variables declaration//GEN-END:variables
}
