/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Wholesaler.Admin;

import Business.Enterprise;
import Business.FDA.FDAEnterprise;
import Business.FDA.EnterpriseLicenseRequest;
import Business.FDA.StateLicensingOrganization;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
import Business.Wholesaler.WholesalerEnterprise;
import Business.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanmankodi
 */
public class ApplyForLicenseJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    WholesalerEnterprise wholeEnt;
    UserAccount ua;
    Network network;

    /**
     * Creates new form ApplyForLicenseJPanel
     */
    public ApplyForLicenseJPanel(JPanel upcJPanel, Network network, WholesalerEnterprise wholeEnt, UserAccount ua) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.wholeEnt = wholeEnt;
        this.ua = ua;
        this.network = network;
        
        nameJTextField.setText(wholeEnt.getEnterpriseName());
        typeJTextField.setText(wholeEnt.getType());
        line1JTextField.setText(wholeEnt.getAddress().getLine1());
        cityJTextField.setText(wholeEnt.getAddress().getCity());
        stateJTextField.setText(wholeEnt.getAddress().getState());
        zipCodeJTextField.setText(String.valueOf(wholeEnt.getAddress().getZipCode()));
        int rowCount = orgJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) orgJTable.getModel()).removeRow(i);
        }
        
        for(Organization o : wholeEnt.getOrganizationDirectory().getOrganizationList()){
            Object row[] = new Object[1];
            row[0] = o.getName();
            ((DefaultTableModel) orgJTable.getModel()).addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        typeJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        applyJButton = new javax.swing.JButton();
        zipCodeJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        stateJTextField = new javax.swing.JTextField();
        cityJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        line1JTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orgJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("State");

        jLabel7.setText("Zip Code");

        jLabel4.setText("Line 1");

        jLabel5.setText("City");

        applyJButton.setText("Apply");
        applyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Enterprise Name");

        jLabel3.setText("Address :");

        jLabel2.setText("Enterprise Type");

        orgJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Organizations"
            }
        ));
        jScrollPane3.setViewportView(orgJTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jLabel4)
                                        .add(jLabel3)
                                        .add(jLabel5)
                                        .add(jLabel6)
                                        .add(jLabel7)))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(typeJTextField)
                                    .add(line1JTextField)
                                    .add(cityJTextField)
                                    .add(stateJTextField)
                                    .add(zipCodeJTextField)))
                            .add(layout.createSequentialGroup()
                                .add(3, 3, 3)
                                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .add(layout.createSequentialGroup()
                        .add(177, 177, 177)
                        .add(applyJButton)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(nameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(typeJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(line1JTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(cityJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(stateJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(zipCodeJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(applyJButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyJButtonActionPerformed
        // TODO add your handling code here:
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof FDAEnterprise) {
                //System.out.println(e);
                ArrayList<Organization> organizationList = e.getOrganizationDirectory().getOrganizationList();
                for (Organization o : organizationList) {
                    if (o instanceof StateLicensingOrganization) {

                        EnterpriseLicenseRequest request = (EnterpriseLicenseRequest) o.getWorkQueue().newWorkRequest(WorkRequest.Type.EnterpriseLicenseRequest);
                        request.setSender(ua);
                        request.setEnt(wholeEnt);
                        request.setStatus(WorkRequest.Status.Sent);
                        request.getEntLic().setAppName(nameJTextField.getText());
                        request.getEntLic().setAppType(typeJTextField.getText());
                        request.getEntLic().setAppLine1(line1JTextField.getText());
                        request.getEntLic().setAppCity(cityJTextField.getText());
                        request.getEntLic().setAppState(stateJTextField.getText());
                        request.getEntLic().setAppZipCode(Integer.parseInt(zipCodeJTextField.getText()));
                        request.getEntLic().setAppOrgList(wholeEnt.getOrganizationDirectory().getOrganizationList());
                        wholeEnt.setId(request.getEntLic().getLicenseNo());
                        JOptionPane.showMessageDialog(null, "Approval Request Generated!!!");
                    }
                }

            }

        }
    }//GEN-LAST:event_applyJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyJButton;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField line1JTextField;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTable orgJTable;
    private javax.swing.JTextField stateJTextField;
    private javax.swing.JTextField typeJTextField;
    private javax.swing.JTextField zipCodeJTextField;
    // End of variables declaration//GEN-END:variables
}
