/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Wholesaler.SalesEmployee;

import Business.Enterprise;
import Business.Network;
import Business.UserAccount;
import Business.Wholesaler.WholesalerEnterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karanmankodi
 */
public class WholesalerSalesEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    WholesalerEnterprise wholeEnt;
    UserAccount ua;
    Network network;
    /**
     * Creates new form WholesalerSalesEmployeeWorkAreaJPanel
     */
    public WholesalerSalesEmployeeWorkAreaJPanel(JPanel upcJPanel, Network network, Enterprise ent, UserAccount ua) {
        
        this.upcJPanel = upcJPanel;
        this.wholeEnt = (WholesalerEnterprise) ent;
        this.ua = ua;
        this.network = network;
        if (wholeEnt.getLicense().equals(Boolean.FALSE)) {
            JOptionPane.showMessageDialog(null, "You are not licensed");
            upcJPanel.removeAll();
            CardLayout card = (CardLayout) upcJPanel.getLayout();
            card.previous(upcJPanel);
        } else {
            initComponents();
        }
        refreshCounter();
    }

    public void refreshCounter(){
        noOfPendingRequestsJTextField.setText(String.valueOf(wholeEnt.getMyOrganization(ua).getWorkQueue().getWorkRequestList().size()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        workQueueJButton = new javax.swing.JButton();
        sentWorkQueueJButton = new javax.swing.JButton();
        displayOrdersJButton = new javax.swing.JButton();
        noOfPendingRequestsJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("--- SALES EMPLOYEE WORK AREA ---");

        workQueueJButton.setText("Work Queue");
        workQueueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workQueueJButtonActionPerformed(evt);
            }
        });

        sentWorkQueueJButton.setText("Sent Work Queue");
        sentWorkQueueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentWorkQueueJButtonActionPerformed(evt);
            }
        });

        displayOrdersJButton.setText("Display Orders");
        displayOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayOrdersJButtonActionPerformed(evt);
            }
        });

        noOfPendingRequestsJTextField.setEditable(false);

        jLabel2.setText("No of Pending Requests");

        refreshJButton.setText("Refresh Counter");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(139, 139, 139)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(displayOrdersJButton)
                            .add(sentWorkQueueJButton))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(refreshJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(noOfPendingRequestsJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(94, 94, 94)
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(140, 140, 140)
                    .add(workQueueJButton)
                    .addContainerGap(180, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel1)
                .add(36, 36, 36)
                .add(displayOrdersJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                .add(sentWorkQueueJButton)
                .add(53, 53, 53)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(noOfPendingRequestsJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(refreshJButton))
                .add(13, 13, 13))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(135, 135, 135)
                    .add(workQueueJButton)
                    .addContainerGap(170, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void workQueueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workQueueJButtonActionPerformed
        // TODO add your handling code here:
        JPanel panel = new WholesalerOrderProcessingJPanel(upcJPanel, network, wholeEnt, ua);
        upcJPanel.add("SalesEmployeeOrderProcessing", panel);
        CardLayout cardLayout = (CardLayout) upcJPanel.getLayout();
        cardLayout.next(upcJPanel);
    }//GEN-LAST:event_workQueueJButtonActionPerformed

    private void sentWorkQueueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentWorkQueueJButtonActionPerformed
        // TODO add your handling code here:
        JPanel panel = new WholesalerSalesEmployeeSentWorkQueueJPanel(upcJPanel, network, wholeEnt, ua);
        upcJPanel.add("SalesEmployeeSentWorkQueue", panel);
        CardLayout cardLayout = (CardLayout) upcJPanel.getLayout();
        cardLayout.next(upcJPanel);
    }//GEN-LAST:event_sentWorkQueueJButtonActionPerformed

    private void displayOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayOrdersJButtonActionPerformed
        // TODO add your handling code here:
        JPanel panel = new WholesalerOrdersDisplayJPanel(upcJPanel, network, wholeEnt, ua);
        upcJPanel.add("Display Orders", panel);
        CardLayout card = (CardLayout)upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_displayOrdersJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        refreshCounter();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayOrdersJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField noOfPendingRequestsJTextField;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton sentWorkQueueJButton;
    private javax.swing.JButton workQueueJButton;
    // End of variables declaration//GEN-END:variables
}
