/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDA.FederalLicensingOrganization;

import UserInterface.FDA.StateLicensingOrganization.*;
import Business.FDA.EnterpriseLicenseRequest;
import Business.FDA.EnterpriseLicenseRequest;
import Business.FDA.FDAEnterprise;
import Business.FDA.FDAEnterprise;
import Business.Network;
import Business.UserAccount;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanmankodi
 */
public class FederalLicensingWorkQueueJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    FDAEnterprise fdaEnt;
    UserAccount ua;
    Network network;

    /**
     * Creates new form FederalLicensingWorkQueueJPanel
     */
    public FederalLicensingWorkQueueJPanel(JPanel upcJPanel, Network network, FDAEnterprise fdaEnt, UserAccount ua) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.fdaEnt = fdaEnt;
        this.ua = ua;
        this.network = network;
        Refresh();
    }

    public void Refresh() {
        int rowCount = licensingRequestJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) licensingRequestJTable.getModel()).removeRow(i);
        }

        ArrayList<WorkRequest> swList = fdaEnt.getFedLicOrg().getWorkQueue().getWorkRequestList();
        for (WorkRequest wr : swList) {
            if (wr.getStatus().equals(WorkRequest.Status.Approved)) {
                break;
            } else {
                Object row[] = new Object[3];
                row[0] = wr;
                row[1] = wr.getEnt();
                row[2] = wr.getEnt().getType();
                ((DefaultTableModel) licensingRequestJTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        licensingRequestJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        viewApplicationJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        licensingRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Enterprise Name", "Enterprise Type"
            }
        ));
        jScrollPane1.setViewportView(licensingRequestJTable);

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        viewApplicationJButton.setText("View Application");
        viewApplicationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewApplicationJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("--- REQUESTS FOR FEDERAL LINCESING ---");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(refreshJButton)
                .add(33, 33, 33)
                .add(viewApplicationJButton))
            .add(jScrollPane1)
            .add(layout.createSequentialGroup()
                .add(78, 78, 78)
                .add(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(viewApplicationJButton)
                    .add(refreshJButton)
                    .add(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void viewApplicationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewApplicationJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = licensingRequestJTable.getSelectedRow();

        EnterpriseLicenseRequest req = (EnterpriseLicenseRequest) licensingRequestJTable.getValueAt(selectedRow, 0);
        
        ViewApplicationJPanel vajp = new ViewApplicationJPanel(upcJPanel, network, fdaEnt, ua, req);
        upcJPanel.add("View Application", vajp);
        CardLayout card = (CardLayout)upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_viewApplicationJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        upcJPanel.remove(this);
        CardLayout card = (CardLayout)upcJPanel.getLayout();
        card.previous(upcJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable licensingRequestJTable;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton viewApplicationJButton;
    // End of variables declaration//GEN-END:variables
}
