/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDA.ClinicalTestingOrganization;

import Business.FDA.ClinicalTestingRequest;
import Business.FDA.FDAEnterprise;
import Business.Network;
import Business.UserAccount;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanmankodi
 */
public class ClinicalTestingWorkQueueJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    FDAEnterprise fdaEnt;
    UserAccount ua;
    Network network;
    /**
     * Creates new form LicensingWorkQueueJPanel
     */
    public ClinicalTestingWorkQueueJPanel(JPanel upcJPanel, Network network, FDAEnterprise fdaEnt, UserAccount ua) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.fdaEnt = fdaEnt;
        this.ua = ua;
        this.network = network;
        Refresh();
    }

    public void Refresh() {
        int rowCount = licensingRequestJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) licensingRequestJTable.getModel()).removeRow(i);
        }

        ArrayList<WorkRequest> swList = fdaEnt.getCderOrg().getClinicalTestingOrg().getWorkQueue().getWorkRequestList();
        for (WorkRequest wr : swList) {
            ClinicalTestingRequest ctr = (ClinicalTestingRequest) wr;
            Object row[] = new Object[3];
            row[0] = ctr;
            row[1] = ctr.getDrugProdReq().getDrug();
            row[2] = ctr.getDrugProdReq().getDrug().getManuEnt();
            ((DefaultTableModel) licensingRequestJTable.getModel()).addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        licensingRequestJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        approveLicenseJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        licensingRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Drug", "Enterprise"
            }
        ));
        jScrollPane1.setViewportView(licensingRequestJTable);

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        approveLicenseJButton.setText("View Clincal Testing Application");
        approveLicenseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveLicenseJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("--- APPLICATIONS FOR CLINICAL TESTS ---");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(refreshJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(approveLicenseJButton)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(85, 85, 85))))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(backJButton)
                    .addContainerGap(373, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(approveLicenseJButton)
                    .add(refreshJButton)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(244, Short.MAX_VALUE)
                    .add(backJButton)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void approveLicenseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveLicenseJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = licensingRequestJTable.getSelectedRow();
        ClinicalTestingRequest request = (ClinicalTestingRequest) licensingRequestJTable.getValueAt(selectedRow, 0);

        ViewClinicalTestJPanel vfijp = new ViewClinicalTestJPanel(upcJPanel, network, fdaEnt, ua, request);
        upcJPanel.add("View Clincal Test", vfijp);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_approveLicenseJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upcJPanel.remove(this);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.previous(upcJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveLicenseJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable licensingRequestJTable;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
