/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDA.ClinicalTestingOrganization;

import Business.Enterprise;
import Business.FDA.ClinicalTestingRequest;
import Business.FDA.DrugApprovalConfirmation;
import Business.FDA.FDAEnterprise;
import Business.Manufacturer.Drug;
import Business.Manufacturer.ManufacturerEnterprise;
import Business.Manufacturer.ManufacturerProductManagementOrganization;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karanmankodi
 */
public class ViewClinicalTestJPanel extends javax.swing.JPanel {

    JPanel upcJPanel;
    FDAEnterprise fdaEnt;
    UserAccount ua;
    Network network;
    ClinicalTestingRequest req;
    Date shell;
    /**
     * Creates new form ViewClinicalTestJPanel
     */
    public ViewClinicalTestJPanel(JPanel upcJPanel, Network network, FDAEnterprise fdaEnt, UserAccount ua, ClinicalTestingRequest req) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.fdaEnt = fdaEnt;
        this.ua = ua;
        this.network = network;
        this.req = req;
        
        nameJTextField.setText(req.getClinicalTestApplication().getIndApp().getDrug().getName());
        manuNameJTextField.setText(req.getClinicalTestApplication().getIndApp().getManuEnt().getEnterpriseName());
        quantityJTextField.setText(String.valueOf(req.getClinicalTestApplication().getIndApp().getDrug().getAvailable()));
        priceJTextField.setText(String.valueOf(req.getClinicalTestApplication().getIndApp().getDrug().getPrice()));
        colorJTextField.setText(req.getClinicalTestApplication().getIndApp().getDrug().getColor());
        shapeTextField.setText(req.getClinicalTestApplication().getIndApp().getDrug().getShape());
        tasteJTextField.setText(req.getClinicalTestApplication().getIndApp().getDrug().getTaste());
        activeIngredientTextField.setText(req.getClinicalTestApplication().getIndApp().getDrug().getActiveIngredient());
        proportionJProgressBar.setValue(req.getClinicalTestApplication().getIndApp().getDrug().getActiveIngredientProportion());
        if (req.getClinicalTestApplication().getIndApp().getSafety().equals(Boolean.TRUE)){
            safetyJTextField.setText("Passed");
        } else {
            safetyJTextField.setText("Failed");
        }
        
        if (req.getClinicalTestApplication().getIndApp().getDesiredEffect().equals(Boolean.TRUE)){
            desiredEffectJTextField.setText("Passed");
        } else {
            desiredEffectJTextField.setText("Failed");
        }
        absorbJTextField.setText(String.valueOf(req.getClinicalTestApplication().getIndApp().getTimeToAbsorb()));
        effectJTextField.setText(String.valueOf(req.getClinicalTestApplication().getIndApp().getTimeForEffect()));
        eliminateJTextField.setText(String.valueOf(req.getClinicalTestApplication().getIndApp().getTimeToEliminate()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        approveLicenseJButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        manuNameJTextField = new javax.swing.JTextField();
        tasteJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        priceJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        proportionJProgressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        activeIngredientTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        eliminateJTextField = new javax.swing.JTextField();
        shapeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        colorJTextField = new javax.swing.JTextField();
        quantityJTextField = new javax.swing.JTextField();
        absorbJTextField = new javax.swing.JTextField();
        effectJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        side1JTextField = new javax.swing.JTextField();
        side2JTextField = new javax.swing.JTextField();
        side3JTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        safetyJTextField = new javax.swing.JTextField();
        desiredEffectJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        shelfLifeJDateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        approveLicenseJButton.setText("Approve");
        approveLicenseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveLicenseJButtonActionPerformed(evt);
            }
        });
        add(approveLicenseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, -1, -1));

        jLabel7.setText("Manufacturer");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 12, -1, -1));

        manuNameJTextField.setEditable(false);
        add(manuNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 6, 253, -1));

        tasteJTextField.setEditable(false);
        add(tasteJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 194, 253, -1));

        jLabel10.setText("Invivo Pre Clinical Tests - Tests on Rats");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 6, -1, -1));

        jLabel11.setText("Time taken to absorb the drug");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 130, -1, -1));

        jLabel8.setText("Safety Check");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 33, -1, -1));

        jLabel9.setText("Desired Effect Check");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 62, -1, -1));

        jLabel12.setText("Time taken for desired effect");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 170, -1, -1));

        jLabel13.setText("Time taken to eliminate drug");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 210, -1, -1));

        priceJTextField.setEditable(false);
        add(priceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 120, 255, -1));

        jLabel3.setText("Price");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 126, -1, -1));

        jLabel16.setText("Proportion");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 294, -1, -1));

        jLabel6.setText("Color");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 160, -1, -1));
        add(proportionJProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 290, 255, -1));

        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 92, -1, -1));

        jLabel15.setText("Active Ingredient");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 262, -1, -1));

        activeIngredientTextField.setEditable(false);
        add(activeIngredientTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 256, 255, -1));

        jLabel14.setText("Pharmacokinetics");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 96, -1, -1));

        eliminateJTextField.setEditable(false);
        add(eliminateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 204, 121, -1));

        shapeTextField.setEditable(false);
        add(shapeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 228, 255, -1));

        jLabel5.setText("Shape");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 234, -1, -1));

        jLabel4.setText("Taste");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 200, -1, -1));

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 52, -1, -1));

        colorJTextField.setEditable(false);
        add(colorJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 154, 253, -1));

        quantityJTextField.setEditable(false);
        add(quantityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 86, 253, -1));

        absorbJTextField.setEditable(false);
        add(absorbJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 124, 121, -1));

        effectJTextField.setEditable(false);
        add(effectJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 164, 121, -1));

        nameJTextField.setEditable(false);
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 46, 253, -1));

        jButton1.setText("Reject");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, -1));

        jLabel17.setText("Noted Side Effects");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 346, -1, -1));
        add(side1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 368, 321, -1));

        side2JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                side2JTextFieldActionPerformed(evt);
            }
        });
        add(side2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 402, 321, -1));
        add(side3JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 436, 321, -1));

        jLabel18.setText("Shelf Life");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 476, -1, -1));

        jLabel19.setText("(YY MM DD)");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 476, -1, -1));

        safetyJTextField.setEditable(false);
        add(safetyJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 27, 201, -1));

        desiredEffectJTextField.setEditable(false);
        add(desiredEffectJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 56, 201, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));
        add(shelfLifeJDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void approveLicenseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveLicenseJButtonActionPerformed
        // TODO add your handling code here:
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof ManufacturerEnterprise) {
                //System.out.println(e);
                ArrayList<Organization> organizationList = e.getOrganizationDirectory().getOrganizationList();
                for (Organization o : organizationList) {
                    if (o instanceof ManufacturerProductManagementOrganization) {
                        ManufacturerProductManagementOrganization mpmo = (ManufacturerProductManagementOrganization)o;
                        DrugApprovalConfirmation conf = (DrugApprovalConfirmation) mpmo.getWorkQueue().newWorkRequest(WorkRequest.Type.DrugApprovalConfirmation);
                        req.getClinicalTestApplication().addSideEffects(side1JTextField.getText());
                        req.getClinicalTestApplication().addSideEffects(side2JTextField.getText());
                        req.getClinicalTestApplication().addSideEffects(side3JTextField.getText());
                        shell = shelfLifeJDateChooser.getDate();
                        req.getClinicalTestApplication().setShelfLife(shell);
                        conf.setCtr(req);
                        Drug approvedDrug = conf.getCtr().getDrugProdReq().getDrug();
                        conf.setSender(ua);
                        conf.setStatus(WorkRequest.Status.Approved);
                        approvedDrug.setClinicalTestApplication(req.getClinicalTestApplication());
                        mpmo.getDrugCatalog().addDrug(approvedDrug);
                        JOptionPane.showMessageDialog(null, "Drug Approved");
                    }
                }

            }

        }
    }//GEN-LAST:event_approveLicenseJButtonActionPerformed

    private void side2JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side2JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_side2JTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upcJPanel.remove(this);
        CardLayout card = (CardLayout)upcJPanel.getLayout();
        card.previous(upcJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absorbJTextField;
    private javax.swing.JTextField activeIngredientTextField;
    private javax.swing.JButton approveLicenseJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField colorJTextField;
    private javax.swing.JTextField desiredEffectJTextField;
    private javax.swing.JTextField effectJTextField;
    private javax.swing.JTextField eliminateJTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField manuNameJTextField;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JProgressBar proportionJProgressBar;
    private javax.swing.JTextField quantityJTextField;
    private javax.swing.JTextField safetyJTextField;
    private javax.swing.JTextField shapeTextField;
    private com.toedter.calendar.JDateChooser shelfLifeJDateChooser;
    private javax.swing.JTextField side1JTextField;
    private javax.swing.JTextField side2JTextField;
    private javax.swing.JTextField side3JTextField;
    private javax.swing.JTextField tasteJTextField;
    // End of variables declaration//GEN-END:variables
}
