/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDA.CDEROrganization;

import Business.FDA.FDAEnterprise;
import Business.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author karanmankodi
 */
public class CDERWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel upcJPanel;
    private FDAEnterprise fdaEnt;
    private UserAccount ua;
    Network network;
    /**
     * Creates new form CDERWorkAreaJPanel
     */
    public CDERWorkAreaJPanel(JPanel upcJPanel, Network network, FDAEnterprise fdaEnt, UserAccount ua) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.fdaEnt = fdaEnt;
        this.ua = ua;
        this.network = network;
        
        fdaJTextField.setText("Food & Drug Administration");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indApplicationJButton = new javax.swing.JButton();
        suspectedDrugsJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fdaJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        indApplicationJButton.setText("Investigational New Drug Applications");
        indApplicationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indApplicationJButtonActionPerformed(evt);
            }
        });

        suspectedDrugsJButton.setText("Suspected Drugs");
        suspectedDrugsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspectedDrugsJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("--- CENTER FOR DRUG EVALUATION & DRUG ---");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(49, 49, 49)
                        .add(indApplicationJButton))
                    .add(layout.createSequentialGroup()
                        .add(109, 109, 109)
                        .add(suspectedDrugsJButton))
                    .add(layout.createSequentialGroup()
                        .add(59, 59, 59)
                        .add(fdaJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(backJButton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(fdaJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(indApplicationJButton)
                .add(46, 46, 46)
                .add(suspectedDrugsJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 71, Short.MAX_VALUE)
                .add(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void indApplicationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indApplicationJButtonActionPerformed
        // TODO add your handling code here:
        INDWorkQueueJPanel indwqjp = new INDWorkQueueJPanel(upcJPanel, network, fdaEnt, ua);
        upcJPanel.add("IND Work Queue", indwqjp);
        CardLayout card = (CardLayout)upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_indApplicationJButtonActionPerformed

    private void suspectedDrugsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspectedDrugsJButtonActionPerformed
        // TODO add your handling code here:
        SuspicionRequestJPanel srjp = new SuspicionRequestJPanel(upcJPanel, network, fdaEnt, ua);
        upcJPanel.add("Suspicion Requests", srjp);
        CardLayout card = (CardLayout)upcJPanel.getLayout();
        card.next(upcJPanel);
    }//GEN-LAST:event_suspectedDrugsJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upcJPanel.remove(this);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.previous(upcJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField fdaJTextField;
    private javax.swing.JButton indApplicationJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton suspectedDrugsJButton;
    // End of variables declaration//GEN-END:variables
}
