/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDA.CDEROrganization;

import Business.Enterprise;
import Business.FDA.FDAEnterprise;
import Business.FDA.ForensicsInvestigationWorkRequest;
import Business.FDA.ForensicsOrganization;
import Business.FDA.ForensicsReport;
import Business.FDA.ReportSuspicionWorkRequest;
import Business.Manufacturer.Drug;
import Business.Manufacturer.ManufacturerEnterprise;
import Business.Network;
import Business.Organization;
import Business.UserAccount;
import Business.Wholesaler.WholesalerEnterprise;
import Business.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karanmankodi
 */
public class EvaluateDrugJPanel extends javax.swing.JPanel {
private JPanel upcJPanel;
    private FDAEnterprise fdaEnt;
    private UserAccount ua;
    Network network;
    ReportSuspicionWorkRequest req;
    /**
     * Creates new form EvaluateDrugJPanel
     */
    public EvaluateDrugJPanel(JPanel upcJPanel, Network network, FDAEnterprise fdaEnt, UserAccount ua, ReportSuspicionWorkRequest req) {
        initComponents();
        this.upcJPanel = upcJPanel;
        this.fdaEnt = fdaEnt;
        this.ua = ua;
        this.network = network;
        this.req = req;
        
        drugJTextField.setText(req.getDrug().getName());
        drugIDJTextField.setText(String.valueOf(req.getDrug().getId()));
        manuJTextField.setText(req.getDrug().getManuEnt().getEnterpriseName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        activeIngredientTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        inactiveProportionJProgressBar = new javax.swing.JProgressBar();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        basicJSlider = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        inactiveIngredientTextField = new javax.swing.JTextField();
        proportionJSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        drugJTextField = new javax.swing.JTextField();
        drugIDJTextField = new javax.swing.JTextField();
        manuJTextField = new javax.swing.JTextField();
        removeSuspicionJButton = new javax.swing.JButton();
        alertAsFakeJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Proportion");

        jLabel18.setText("Inactive Ingredient");

        jLabel16.setText("Proportion");

        jLabel15.setText("Active Ingredient");

        jLabel8.setText("Basic");

        jLabel9.setText("Acidic");

        jLabel1.setText("Drug Name");

        jLabel2.setText("Drug ID");

        jLabel3.setText("Manufacturer");

        drugJTextField.setEditable(false);

        drugIDJTextField.setEditable(false);

        manuJTextField.setEditable(false);

        removeSuspicionJButton.setText("Remove Suspicion");
        removeSuspicionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSuspicionJButtonActionPerformed(evt);
            }
        });

        alertAsFakeJButton.setText("Alert as Fake");
        alertAsFakeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertAsFakeJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel15)
                            .add(jLabel16))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(activeIngredientTextField)
                            .add(proportionJSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(drugJTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .add(drugIDJTextField)
                            .add(manuJTextField))))
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jLabel18)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inactiveIngredientTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel8)
                    .add(jLabel17))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(inactiveProportionJProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(basicJSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel9))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(backJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(removeSuspicionJButton)
                .add(39, 39, 39)
                .add(alertAsFakeJButton)
                .add(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(drugJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(drugIDJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(manuJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(activeIngredientTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel16)
                    .add(proportionJSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(inactiveIngredientTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel18))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel17)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, inactiveProportionJProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jLabel8))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, basicJSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9))
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(removeSuspicionJButton)
                    .add(alertAsFakeJButton)
                    .add(backJButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeSuspicionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSuspicionJButtonActionPerformed
        // TODO add your handling code here:
        req.setStatus(WorkRequest.Status.DrugCleared);
        req.getDrug().setLicense(Boolean.TRUE);
        JOptionPane.showMessageDialog(null, "Drug Cleared from Suspicion");
    }//GEN-LAST:event_removeSuspicionJButtonActionPerformed

    private void alertAsFakeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertAsFakeJButtonActionPerformed
        // TODO add your handling code here:
        req.setStatus(WorkRequest.Status.DrugBarred);
        Drug drug = req.getDrug();
        drug.getManuEnt().getProdMgmtOrg().getDrugCatalog().discontiueDrug(drug);
        Business.Business.getInstance().addFakeDrug(drug);
        for (Network n : Business.Business.getInstance().getNetworkDritectory().getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof ManufacturerEnterprise) {
                    if (e.equals(drug.getManuEnt())) {
                        e.setLicense(Boolean.FALSE);
                    }
                }
            }
        }
        for (Network n : Business.Business.getInstance().getNetworkDritectory().getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof WholesalerEnterprise) {
                    if (e.equals(drug.getWholeEnt())) {
                        e.setLicense(Boolean.FALSE);
                    }
                }
            }
        }

        // Initiating investigation
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (ent instanceof FDAEnterprise) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof ForensicsOrganization) {
                        ForensicsInvestigationWorkRequest request = new ForensicsInvestigationWorkRequest();
                        org.getWorkQueue().addRequest(request);
                        request.setForensicReportDir(fdaEnt.getDir());
                        ForensicsReport newForensicReport = request.newForensicReport(drug, fdaEnt);
                        request.setD(drug);
                        newForensicReport.setClinicalTestApplication(drug.getClinicalTestApplication());
                        request.setSender(ua);
                        request.setStatus(WorkRequest.Status.Investigation);
                        newForensicReport.setActiveIngredient(activeIngredientTextField.getText());
                        newForensicReport.setActiveIngProportion(proportionJSlider1.getValue());
                        newForensicReport.setInactiveIngredient(inactiveIngredientTextField.getText());
                        newForensicReport.setInactiveIngProportion(100 - newForensicReport.getActiveIngProportion());
                        inactiveProportionJProgressBar.setValue(newForensicReport.getInactiveIngProportion());
                        newForensicReport.setBasicContent(basicJSlider.getValue());
                        newForensicReport.setAcidicContent(100 - basicJSlider.getValue());
                        newForensicReport.setDrug(drug);
                        newForensicReport.setEnt(fdaEnt);

                    }
                }
            }
        }

        JOptionPane.showMessageDialog(null, "Drug reported as fake");
    }//GEN-LAST:event_alertAsFakeJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upcJPanel.remove(this);
        CardLayout card = (CardLayout) upcJPanel.getLayout();
        card.previous(upcJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activeIngredientTextField;
    private javax.swing.JButton alertAsFakeJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JSlider basicJSlider;
    private javax.swing.JTextField drugIDJTextField;
    private javax.swing.JTextField drugJTextField;
    private javax.swing.JTextField inactiveIngredientTextField;
    private javax.swing.JProgressBar inactiveProportionJProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField manuJTextField;
    private javax.swing.JSlider proportionJSlider1;
    private javax.swing.JButton removeSuspicionJButton;
    // End of variables declaration//GEN-END:variables
}
